# 基础镜像
FROM redis
# author
MAINTAINER vrmlstudio

# 挂载目录
VOLUME /home/vrmlstudio/redis
# 创建目录
RUN mkdir -p /home/vrmlstudio/redis
# 指定路径
WORKDIR /home/vrmlstudio/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/vrmlstudio/redis/redis.conf
