version : '3.8'
services:
#  vrmlstudio-nacos:
#    container_name: vrmlstudio-nacos
#    image: nacos/nacos-server
#    build:
#      context: docker/nacos
#    environment:
#      - MODE=standalone
#    volumes:
#      - ./docker/nacos/logs/:/home/nacos/logs
#      - ./docker/nacos/conf/application.properties:/home/nacos/conf/application.properties
#    ports:
#      - "8848:8848"
#      - "9848:9848"
#      - "9849:9849"
#    depends_on:
#      - vrmlstudio-mysql
#    links:
#      - vrmlstudio-mysql
#  vrmlstudio-mysql:
#    container_name: vrmlstudio-mysql
#    image: mysql:8.0.26
#    build:
#      context: sql
#      dockerfile: Dockerfile
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./docker/mysql/conf:/etc/mysql/conf.d
#      - ./docker/mysql/logs:/logs
#      - ./docker/mysql/data:/var/lib/mysql
#    command: [
#          'mysqld',
#          '--innodb-buffer-pool-size=80M',
#          '--character-set-server=utf8mb4',
#          '--collation-server=utf8mb4_unicode_ci',
#          '--default-time-zone=+8:00',
#          '--lower-case-table-names=1'
#        ]
#    environment:
#      MYSQL_DATABASE: 'xy-cloud'
#      MYSQL_ROOT_PASSWORD: password
#  vrmlstudio-redis:
#    container_name: vrmlstudio-redis
#    image: redis
#    build:
#      context: docker/redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./docker/redis/conf/redis.conf:/home/vrmlstudio/redis/redis.conf
#      - ./docker/redis/data:/data
#    command: redis-server /home/vrmlstudio/redis/redis.conf
  vrmlstudio-gateway:
    container_name: vrmlstudio-gateway
    build:
      context: vrmlstudio-gateway
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
#    depends_on:
#      - vrmlstudio-nacos
#      - vrmlstudio-redis
#    links:
#      - vrmlstudio-nacos
#      - vrmlstudio-redis
  vrmlstudio-auth:
    container_name: vrmlstudio-auth
    build:
      context: vrmlstudio-auth
      dockerfile: ./Dockerfile
    ports:
      - "9200:9200"
#    depends_on:
#      - vrmlstudio-nacos
#      - vrmlstudio-redis
#    links:
#      - vrmlstudio-nacos
#      - vrmlstudio-redis
  vrmlstudio-modules-tenant:
    container_name: vrmlstudio-modules-tenant
    build:
      context: vrmlstudio-modules/vrmlstudio-tenant
      dockerfile: ./Dockerfile
    ports:
      - "9700:9700"
#    depends_on:
#      - vrmlstudio-nacos
#      - vrmlstudio-redis
#      - vrmlstudio-mysql
#    links:
#      - vrmlstudio-nacos
#      - vrmlstudio-redis
#      - vrmlstudio-mysql
  vrmlstudio-modules-system:
    container_name: vrmlstudio-modules-system
    build:
      context: vrmlstudio-modules/vrmlstudio-system
      dockerfile: ./Dockerfile
    ports:
      - "9600:9600"
#    depends_on:
#      - vrmlstudio-nacos
#      - vrmlstudio-redis
#      - vrmlstudio-mysql
#    links:
#      - vrmlstudio-nacos
#      - vrmlstudio-redis
#      - vrmlstudio-mysql
  vrmlstudio-modules-gen:
    container_name: vrmlstudio-modules-gen
    build:
      context: vrmlstudio-modules/vrmlstudio-gen
      dockerfile: ./Dockerfile
    ports:
      - "9400:9400"
#    depends_on:
#      - vrmlstudio-nacos
#      - vrmlstudio-redis
#      - vrmlstudio-mysql
#    links:
#      - vrmlstudio-nacos
#      - vrmlstudio-redis
#      - vrmlstudio-mysql
  vrmlstudio-modules-job:
    container_name: vrmlstudio-modules-job
    build:
      context: vrmlstudio-modules/vrmlstudio-job
      dockerfile: ./Dockerfile
    ports:
      - "9500:9500"
#    depends_on:
#      - vrmlstudio-nacos
#      - vrmlstudio-redis
#      - vrmlstudio-mysql
#    links:
#      - vrmlstudio-nacos
#      - vrmlstudio-redis
#      - vrmlstudio-mysql
  vrmlstudio-modules-file:
    container_name: vrmlstudio-modules-file
    build:
      context: vrmlstudio-modules/vrmlstudio-file
      dockerfile: ./Dockerfile
    ports:
      - "9300:9300"
    volumes:
    - ./vrmlstudio/uploadPath:/home/vrmlstudio/uploadPath
  vrmlstudio-visual-monitor:
    container_name: vrmlstudio-visual-monitor
    build:
      context: vrmlstudio-visual/vrmlstudio-monitor
      dockerfile: ./Dockerfile
    ports:
      - "9100:9100"